kind: Service
apiVersion: v1
metadata:
  name: contenedorkubernetes #Nombre del service/contenedor
  labels:
    app: contenedorkubernetes
spec:
  ports:
    - port: 8080 #Puerto expuesto del contenedor, para acceder desde internet
      targetPort: 80 #Puerto interno del pod
      nodePort: 31200 #Para acceder a el si estamos dentro del cl√∫ster desde cualquier nodo
  selector:
    app: proyectokubernetes #A que pod/Deployment pertenece
  type: LoadBalancer #Para que nuestro servicio pueda ser visto fuera del cluster, es decir internet
